-- Muestra el porcentaje de ocupación de cada ciudad en su respectiva ciudad.
SELECT CONCAT(C.NOMBRE_CIUDAD,' ',D.NOMBRE_DIRECCION) DIRECCION,
    S.NOMBRE_SUCURSAL SUCURSAL,
    ROUND(CAST(COUNT(DISTINCT R.K_RESERVA) AS DECIMAL) / COUNT(DISTINCT SP.K_SLOT_PARQUEADERO), 2) PORCENTAJE
FROM PARQUEADERO.PAIS P 
    INNER JOIN PARQUEADERO.DEPARTAMENTO DP ON P.K_PAIS = DP.K_PAIS
    INNER JOIN PARQUEADERO.CIUDAD C ON DP.K_DEPARTAMENTO = C.K_DEPARTAMENTO
    INNER JOIN PARQUEADERO.DIRECCION D ON C.K_CIUDAD = D.K_CIUDAD
    INNER JOIN PARQUEADERO.SUCURSAL S ON D.K_DIRECCION = S.K_DIRECCION
    INNER JOIN PARQUEADERO.TARIFA_MINUTO TM ON S.K_SUCURSAL = TM.K_SUCURSAL
    INNER JOIN PARQUEADERO.SLOT_PARQUEADERO SP ON S.K_SUCURSAL = SP.K_SUCURSAL
    INNER JOIN PARQUEADERO.HORARIO_SUCURSAL HS ON S.K_SUCURSAL = HS.K_SUCURSAL
    INNER JOIN PARQUEADERO.DIA_SEMANA DS ON HS.K_DIA_SEMANA = DS.K_DIA_SEMANA
LEFT JOIN (
    SELECT K_SLOT_PARQUEADERO,
        K_SUCURSAL,
        K_RESERVA
    FROM PARQUEADERO.RESERVA
    WHERE ESTA_ACTIVA = TRUE
) R ON SP.K_SLOT_PARQUEADERO = R.K_SLOT_PARQUEADERO
    AND SP.K_SUCURSAL = R.K_SUCURSAL
    AND S.K_SUCURSAL = R.K_SUCURSAL
GROUP BY C.NOMBRE_CIUDAD,
    D.NOMBRE_DIRECCION,
    S.NOMBRE_SUCURSAL;

-- Cantidad de reservas por período de tiempo
SELECT DISTINCT R.FECHA_INICIO_RESERVA FECHA_RESERVA,
    EXTRACT(HOUR FROM FECHA_INICIO_RESERVA) HORA,
    EXTRACT(MINUTE FROM FECHA_INICIO_RESERVA) MINUTO,
    C.NOMBRE_CIUDAD CIUDAD,
    S.NOMBRE_SUCURSAL SUCURSAL
FROM PARQUEADERO.PAIS P 
    INNER JOIN PARQUEADERO.DEPARTAMENTO DP ON P.K_PAIS = DP.K_PAIS
    INNER JOIN PARQUEADERO.CIUDAD C ON DP.K_DEPARTAMENTO = C.K_DEPARTAMENTO
    INNER JOIN PARQUEADERO.DIRECCION D ON C.K_CIUDAD = D.K_CIUDAD
    INNER JOIN PARQUEADERO.SUCURSAL S ON D.K_DIRECCION = S.K_DIRECCION
    INNER JOIN PARQUEADERO.TARIFA_MINUTO TM ON S.K_SUCURSAL = TM.K_SUCURSAL
    INNER JOIN PARQUEADERO.SLOT_PARQUEADERO SP ON S.K_SUCURSAL = SP.K_SUCURSAL
    INNER JOIN PARQUEADERO.HORARIO_SUCURSAL HS ON S.K_SUCURSAL = HS.K_SUCURSAL
    INNER JOIN PARQUEADERO.DIA_SEMANA DS ON HS.K_DIA_SEMANA = DS.K_DIA_SEMANA
    INNER JOIN PARQUEADERO.RESERVA R ON SP.K_SLOT_PARQUEADERO = R.K_SLOT_PARQUEADERO
        AND SP.K_SUCURSAL = R.K_SUCURSAL
        AND S.K_SUCURSAL = R.K_SUCURSAL;

-- Comparación de ganancias entre sucursales
SELECT DISTINCT R.VALOR_RESERVA VALOR_RESERVA,
    C.NOMBRE_CIUDAD CIUDAD,
    S.NOMBRE_SUCURSAL SUCURSAL
FROM PARQUEADERO.PAIS P 
    INNER JOIN PARQUEADERO.DEPARTAMENTO DP ON P.K_PAIS = DP.K_PAIS
    INNER JOIN PARQUEADERO.CIUDAD C ON DP.K_DEPARTAMENTO = C.K_DEPARTAMENTO
    INNER JOIN PARQUEADERO.DIRECCION D ON C.K_CIUDAD = D.K_CIUDAD
    INNER JOIN PARQUEADERO.SUCURSAL S ON D.K_DIRECCION = S.K_DIRECCION
    INNER JOIN PARQUEADERO.TARIFA_MINUTO TM ON S.K_SUCURSAL = TM.K_SUCURSAL
    INNER JOIN PARQUEADERO.SLOT_PARQUEADERO SP ON S.K_SUCURSAL = SP.K_SUCURSAL
    INNER JOIN PARQUEADERO.HORARIO_SUCURSAL HS ON S.K_SUCURSAL = HS.K_SUCURSAL
    INNER JOIN PARQUEADERO.DIA_SEMANA DS ON HS.K_DIA_SEMANA = DS.K_DIA_SEMANA
    INNER JOIN PARQUEADERO.RESERVA R ON SP.K_SLOT_PARQUEADERO = R.K_SLOT_PARQUEADERO
        AND SP.K_SUCURSAL = R.K_SUCURSAL
        AND S.K_SUCURSAL = R.K_SUCURSAL
WHERE R.VALOR_RESERVA IS NOT NULL;

-- 