-- Vista materializada para mostrar todas las sucursales con su ciudad, dirección y tipo de sucursal.
CREATE MATERIALIZED VIEW PARQUEADERO.SUCURSAL_INFO TABLESPACE PARKUD_DEF AS
SELECT
    C.NOMBRE_CIUDAD "Ciudad",
    DIR.EDIFICIO_DIRECCION || ', ' || DIR.NOMBRE_DIRECCION || ', ' || DIR.CODIGO_POSTAL "Dirección",
    S.NOMBRE_SUCURSAL || ' (' || S.TIPO_SUCURSAL || ')' "Sucursal"
FROM
    PARQUEADERO.PAIS P,
    PARQUEADERO.DEPARTAMENTO D,
    PARQUEADERO.CIUDAD C,
    PARQUEADERO.DIRECCION DIR,
    PARQUEADERO.SUCURSAL S
WHERE
    P.K_PAIS = D.K_PAIS
    AND D.K_DEPARTAMENTO = C.K_DEPARTAMENTO
    AND DIR.K_CIUDAD = C.K_CIUDAD
    AND S.K_SUCURSAL = DIR.K_SUCURSAL;

COMMENT ON MATERIALIZED VIEW PARQUEADERO.SUCURSAL_INFO IS E'Vista que muestra la información de todas las sucursales.';

ALTER MATERIALIZED VIEW PARQUEADERO.SUCURSAL_INFO OWNER TO PARKUD_DB_ADMIN;

GRANT SELECT ON TABLE PARQUEADERO.SUCURSAL_INFO TO USER_ROLE;

-- ddl-end --
-- Vista para filtro de parqueaderos de una sucursal siguiendo los Mockups ya creados
CREATE VIEW PARQUEADERO.FILTRO_RESERVA_PARQUEADERO TABLESPACE PARKUD_DEF AS
SELECT
    C.NOMBRE_CIUDAD "Ciudad",
    DIR.EDIFICIO_DIRECCION || ', ' || DIR.NOMBRE_DIRECCION "Dirección",
    S.NOMBRE_SUCURSAL || ' (' || S.TIPO_SUCURSAL || ')' "Sucursal",
    SP.TIPO_PARQUEADERO "Tipo parqueadero",
    SP.K_SLOT_PARQUEADERO "Parqueadero"
FROM
    PARQUEADERO.PAIS P,
    PARQUEADERO.DEPARTAMENTO D,
    PARQUEADERO.CIUDAD C,
    PARQUEADERO.DIRECCION DIR,
    PARQUEADERO.SUCURSAL S,
    PARQUEADERO.SLOT_PARQUEADERO SP
WHERE
    P.K_PAIS = D.K_PAIS
    AND D.K_DEPARTAMENTO = C.K_DEPARTAMENTO
    AND DIR.K_CIUDAD = C.K_CIUDAD
    AND S.K_SUCURSAL = DIR.K_SUCURSAL
    AND S.K_SUCURSAL = SP.K_SUCURSAL;

COMMENT ON MATERIALIZED VIEW PARQUEADERO.SUCURSAL_INFO IS E'Vista utilizada para filtrar un parqueadero.';

ALTER MATERIALIZED VIEW PARQUEADERO.SUCURSAL_INFO OWNER TO PARKUD_DB_ADMIN;

GRANT SELECT ON TABLE PARQUEADERO.SUCURSAL_INFO TO USER_ROLE;

-- ddl-end --
-- Vista para filtro de parqueaderos de una sucursal siguiendo los Mockups ya creados
CREATE VIEW PARQUEADERO.FILTRO_DISPONIBILIDAD_PARQUEADERO TABLESPACE PARKUD_DEF AS
SELECT
    C.NOMBRE_CIUDAD "Ciudad",
    DIR.EDIFICIO_DIRECCION || ', ' || DIR.NOMBRE_DIRECCION "Ubicación",
    S.NOMBRE_SUCURSAL || ' (' || S.TIPO_SUCURSAL || ')' "Sucursal",
    HS.HORA_ABIERTO_SUCURSAL "Apertura",
    HS.HORA_CERRADO_SUCURSAL "Cierre"
FROM
    PARQUEADERO.PAIS P
    INNER JOIN PARQUEADERO.DEPARTAMENTO D ON P.K_PAIS = D.K_PAIS
    INNER JOIN PARQUEADERO.CIUDAD C ON D.K_DEPARTAMENTO = C.K_DEPARTAMENTO
    INNER JOIN PARQUEADERO.DIRECCION DIR ON DIR.K_CIUDAD = C.K_CIUDAD
    INNER JOIN PARQUEADERO.SUCURSAL S ON S.K_SUCURSAL = DIR.K_SUCURSAL
    INNER JOIN PARQUEADERO.SLOT_PARQUEADERO SP ON S.K_SUCURSAL = SP.K_SUCURSAL
    INNER JOIN PARQUEADERO.HORARIO_SUCURSAL HS ON HS.K_SUCURSAL = S.K_SUCURSAL
    INNER JOIN PARQUEADERO.DIA_SEMANA DS ON HS.K_DIA_SEMANA = DS.K_DIA_SEMANA;

COMMENT ON MATERIALIZED VIEW PARQUEADERO.SUCURSAL_INFO IS E'Vista utilizada para filtrar un parqueadero.';

ALTER MATERIALIZED VIEW PARQUEADERO.SUCURSAL_INFO OWNER TO PARKUD_DB_ADMIN;

GRANT SELECT ON TABLE PARQUEADERO.SUCURSAL_INFO TO USER_ROLE;

-- ddl-end --
SELECT
    COUNT(ESTA_DISPONIBLE) -(
        SELECT
            COUNT(ESTA_DISPONIBLE)
        FROM
            PARQUEADERO.SUCURSAL S
            INNER JOIN PARQUEADERO.SLOT_PARQUEADERO SP ON S.K_SUCURSAL = SP.K_SUCURSAL
            INNER JOIN PARQUEADERO.RESERVA_PARQUEADERO RP ON SP.K_SLOT_PARQUEADERO = RP.K_SLOT_PARQUEADERO
                AND SP.K_SUCURSAL = RP.K_SUCURSAL
            INNER JOIN PARQUEADERO.RESERVA R ON R.K_RESERVA = RP.K_RESERVA
        WHERE
            R.FECHA_INICIO_RESERVA >(
                SELECT
                    CURRENT_TIMESTAMP)
                AND R.ESTA_ACTIVA) TEST_COLUMN
    FROM
        PARQUEADERO.SLOT_PARQUEADERO SP;

